name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 New Features'
    labels:
      - 'client:feature'

  - title: '🐛 Fixes'
    labels:
      - 'client:fix'
      - 'client:bug'

  - title: '🧪 Tests'
    labels:
      - 'client:tests'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES
